In [1]:
import pandas as pd
import numpy as np
from tpot import TPOTRegressor
from sklearn.model_selection import train_test_split

In [2]:
airdata = pd.read_csv('airdata.csv', sep=',', dtype=np.float64)
airdata

date  hour  pm25    O3  pm10   so2   no2   co    温度   风力    天气  \
0    20180219.0   0.0  22.0  48.0  26.0   3.0  25.0  0.7   4.7  2.0  60.0   
1    20180219.0   1.0  13.0  54.0  26.0   3.0  19.0  0.7   4.4  2.0  10.0   
2    20180219.0   2.0   9.0  53.0  20.0   3.0  20.0  0.7   4.7  2.0  10.0   
3    20180219.0   3.0  14.0  62.0  20.0   3.0  15.0  0.6   4.9  2.0  60.0   
4    20180219.0   4.0  18.0  66.0  25.0   3.0  14.0  0.6   5.3  2.0   0.0   
5    20180219.0   5.0  16.0  61.0  28.0   5.0  24.0  0.6   5.3  2.0  10.0   
6    20180219.0   6.0  15.0  61.0  24.0   6.0  24.0  0.6   5.6  2.0  60.0   
7    20180219.0   7.0  21.0  42.0  29.0   8.0  41.0  0.6   6.0  2.0   0.0   
8    20180219.0   8.0  18.0  25.0  32.0   8.0  56.0  0.6   6.2  2.0   0.0   
9    20180219.0   9.0  23.0  37.0  32.0   6.0  46.0  0.7   5.8  2.0  60.0   
10   20180219.0  10.0  22.0  34.0  34.0   4.0  48.0  0.7   5.5  2.0  10.0   
11   20180219.0  11.0  18.0  37.0  21.0   4.0  48.0  0.7   5.4  2.0  10.0   
12   20180219.0  12.0  22.0  39.0  25.0   4.0  45.0  0.7   5.2  2.0   0.0   
13   20180219.0  13.0  16.0  43.0  20.0   4.0  43.0  0.7   5.0  2.0  10.0   
14   20180219.0  14.0  20.0  47.0  20.0   4.0  40.0  0.7   4.9  2.0  10.0   
15   20180219.0  15.0  13.0  52.0  17.0   3.0  38.0  0.7   5.0  2.0  10.0   
16   20180219.0  16.0  16.0  48.0  18.0   3.0  44.0  0.7   4.8  2.0  10.0   
17   20180219.0  17.0  18.0  41.0  27.0   4.0  52.0  0.7   4.8  2.0  10.0   
18   20180219.0  18.0  16.0  49.0  25.0   5.0  43.0  0.8   4.8  2.0  10.0   
19   20180219.0  19.0  17.0  56.0  29.0   4.0  38.0  0.8   4.8  2.0  10.0   
20   20180219.0  20.0  23.0  55.0  31.0   4.0  34.0  0.8   4.4  2.0  10.0   
21   20180219.0  21.0  19.0  71.0  29.0   6.0  30.0  0.8   4.4  2.0  10.0   
22   20180219.0  22.0  38.0  77.0  47.0   8.0  29.0  0.9   4.5  2.0  10.0   
23   20180220.0  23.0  46.0  72.0  56.0   8.0  31.0  0.9   4.2  2.0  10.0   
24   20180220.0   0.0  50.0  67.0  58.0  10.0  34.0  0.9   4.4  3.0  10.0   
25   20180220.0   1.0  57.0  47.0  76.0  13.0  41.0  0.9   4.9  3.0  10.0   
26   20180220.0   2.0  61.0  51.0  77.0  13.0  38.0  0.9   5.3  3.0  10.0   
27   20180220.0   3.0  61.0  58.0  87.0  15.0  36.0  1.0   5.3  2.0  60.0   
28   20180220.0   4.0  75.0  48.0  95.0  14.0  36.0  1.0   5.2  2.0  10.0   
29   20180220.0   5.0  73.0  54.0  87.0  10.0  31.0  0.9   5.0  2.0  10.0   
..          ...   ...   ...   ...   ...   ...   ...  ...   ...  ...   ...   
282  20180302.0  18.0  35.0  64.0  55.0   2.0  48.0  0.5   8.0  2.0  10.0   
283  20180302.0  19.0  33.0  65.0  59.0   1.0  47.0  0.5   8.2  2.0  10.0   
284  20180302.0  20.0  35.0  63.0  53.0   1.0  43.0  0.5   8.2  1.0  10.0   
285  20180302.0  21.0  46.0  62.0  60.0   1.0  44.0  0.5   8.2  1.0  10.0   
286  20180302.0  22.0  36.0  61.0  51.0   2.0  41.0  0.5   8.4  2.0  10.0   
287  20180302.0  23.0  34.0  61.0  56.0   2.0  37.0  0.5   8.5  2.0  10.0   
288  20180303.0   0.0  40.0  60.0  55.0   2.0  33.0  0.5   8.9  2.0  10.0   
289  20180303.0   1.0  41.0  55.0  63.0   2.0  27.0  0.5   9.7  2.0  10.0   
290  20180303.0   2.0  46.0  47.0  64.0   2.0  31.0  0.5  10.7  2.0  10.0   
291  20180303.0   3.0  45.0  41.0  67.0   2.0  31.0  0.5  12.0  2.0  10.0   
292  20180303.0   4.0  47.0  35.0  68.0   1.0  36.0  0.6  13.4  2.0  10.0   
293  20180303.0   5.0  45.0  28.0  59.0   2.0  39.0  0.7  15.8  3.0   0.0   
294  20180303.0   6.0  50.0  27.0  65.0   2.0  37.0  0.7  17.2  2.0   0.0   
295  20180303.0   7.0  48.0  11.0  65.0   1.0  49.0  0.7  15.3  2.0   5.0   
296  20180303.0   8.0  45.0  13.0  66.0   2.0  54.0  0.7  18.1  2.0   0.0   
297  20180303.0   9.0  51.0  21.0  73.0   2.0  49.0  0.7  18.0  3.0   0.0   
298  20180303.0  10.0  49.0  30.0  73.0   3.0  44.0  0.7  16.0  3.0   5.0   
299  20180303.0  11.0  48.0  36.0  73.0   3.0  46.0  0.8  14.5  3.0  10.0   
300  20180303.0  12.0  48.0  46.0  64.0   3.0  46.0  0.8  13.6  2.0  10.0   
301  20180303.0  13.0  40.0  65.0  66.0   3.0  38.0  0.7  13.5  3.0  10.0   
302  20

In [3]:
y = airdata['pm25'].values
#y = airdata.iloc[:,2]
#y.shape
#y = np.array(y)
#y = y.reshape(y.size)
y.shape
#y

(312,)

In [4]:
X = airdata.drop('pm25', axis=1).values
X.shape
#X

(312, 13)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=None)

In [6]:
X_train

array([[2.0180219e+07, 1.9000000e+01, 5.6000000e+01, ..., 8.9000000e+01,
        1.0188000e+03, 0.0000000e+00],
       [2.0180302e+07, 1.7000000e+01, 7.0000000e+01, ..., 9.5000000e+01,
        1.0053000e+03, 0.0000000e+00],
       [2.0180225e+07, 1.4000000e+01, 9.5000000e+01, ..., 7.7000000e+01,
        1.0220000e+03, 0.0000000e+00],
       ...,
       [2.0180227e+07, 2.0000000e+01, 1.0400000e+02, ..., 1.0400000e+01,
        1.0027000e+03, 5.0000000e-01],
       [2.0180301e+07, 1.9000000e+01, 8.8000000e+01, ..., 4.2000000e+00,
        1.0139000e+03, 5.0000000e-01],
       [2.0180224e+07, 1.0000000e+01, 2.9000000e+01, ..., 5.9000000e+01,
        1.0188000e+03, 0.0000000e+00]])

In [7]:
X_test

array([[2.0180226e+07, 1.8000000e+01, 7.7000000e+01, ..., 7.6000000e+00,
        1.0157000e+03, 0.0000000e+00],
       [2.0180225e+07, 1.7000000e+01, 8.2000000e+01, ..., 5.5000000e+00,
        1.0214000e+03, 0.0000000e+00],
       [2.0180225e+07, 1.5000000e+01, 8.8000000e+01, ..., 7.8000000e+01,
        1.0216000e+03, 0.0000000e+00],
       ...,
       [2.0180227e+07, 2.0000000e+00, 2.0000000e+01, ..., 1.2200000e+01,
        1.0150000e+03, 0.0000000e+00],
       [2.0180302e+07, 4.0000000e+00, 7.2000000e+01, ..., 7.7000000e+00,
        1.0121000e+03, 0.0000000e+00],
       [2.0180303e+07, 1.5000000e+01, 9.2000000e+01, ..., 9.3000000e+01,
        1.0050000e+03, 0.0000000e+00]])

In [8]:
y_train

array([ 17.,  34.,  75.,  35.,  91.,  27.,  26.,  72.,   9.,  71.,  32.,
        68.,  40.,  69.,  78.,  46.,  28.,  44.,  62.,  19.,  41.,  71.,
        58.,  58.,  53.,  49.,  47.,  82.,  21.,  40.,  31.,  32.,  80.,
        35.,  40.,  63.,  35.,  44.,  76.,  79.,  50.,  16.,  27.,  57.,
        59.,  51.,  30.,  20.,  56.,  59.,  73.,  67.,  25.,  70.,  34.,
        29.,  40.,  26.,  48.,  82.,  38.,  60.,  70.,  40.,  39.,  36.,
        49.,  46.,  64.,  71.,  33.,  22.,  71.,  54.,  44.,  40.,  21.,
        53.,  18.,  35.,  36.,  65.,  43.,  47.,  23.,  65.,  34.,  13.,
        67.,  63.,  32.,  71.,  54.,  82.,  71.,  67.,  57.,  50.,  30.,
        32.,  80.,  46.,  48.,  69.,  18.,  66.,  92.,  81.,  23.,  86.,
        47.,  47.,  37.,  76.,  33.,  26.,  34.,  29.,  22.,  48.,  32.,
        79.,  25.,  44.,  42.,  39.,  75.,  25.,  58.,  25.,  46.,  71.,
        59.,  61.,  18.,  74.,  60.,  81.,  38.,  56.,  29.,  72.,  24.,
        20.,  62.,  74.,  34.,  16.,  34.,  67.,  1

In [9]:
y_test

array([ 28.,  58.,  72.,  40.,  45.,  80.,  51.,  53.,  57.,  80.,  59.,
        60.,  63.,  65.,  52.,  51.,  85.,  74.,  27.,  57.,  35.,  60.,
        57.,  48.,  27.,  41.,  63.,  30.,  78.,  30.,  70.,  48.,  78.,
        14.,  62.,  22.,  51.,  23.,  15.,  33.,  68.,  77.,  57.,  15.,
        30.,  28.,  59.,  53.,  51.,  20.,  73.,  18.,  55.,  31.,  38.,
        63.,  75.,  19.,  45.,  30.,  38.,  12., 110.,  73.,  49.,  66.,
        86.,  69.,  26.,  61.,  60.,  31., 108.,  45.,  31.,  36.,  30.,
        31.])

In [10]:
tpot = TPOTRegressor(scoring='neg_mean_absolute_error',
                     max_time_mins=5,
                     n_jobs=-1,
                     verbosity=2,
                     cv=5)

In [11]:
tpot.fit(X_train, y_train)

Generation 1 - Current best internal CV score: -4.7849486734776665
Generation 2 - Current best internal CV score: -4.7849486734776665
Generation 3 - Current best internal CV score: -4.7849486734776665
Generation 4 - Current best internal CV score: -4.776623866790009
Generation 5 - Current best internal CV score: -4.521113332991166
Generation 6 - Current best internal CV score: -4.443235406132741
Generation 7 - Current best internal CV score: -4.430525531914894
Generation 8 - Current best internal CV score: -4.430525531914894
Generation 9 - Current best internal CV score: -4.430525531914894
Generation 10 - Current best internal CV score: -4.430525531914894
Generation 11 - Current best internal CV score: -4.430525531914894
Generation 12 - Current best internal CV score: -4.430525531914894

5.04568995 minutes have elapsed. TPOT will close down.
TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: ExtraTreesRegressor(LassoLarsCV(MaxAbsScaler(input_matrix), normalize

TPOTRegressor(config_dict=None, crossover_rate=0.1, cv=5,
       disable_update_check=False, early_stop=None, generations=1000000,
       max_eval_time_mins=5, max_time_mins=5, memory=None,
       mutation_rate=0.9, n_jobs=-1, offspring_size=None,
       periodic_checkpoint_folder=None, population_size=100,
       random_state=None, scoring='neg_mean_absolute_error', subsample=1.0,
       use_dask=False, verbosity=2, warm_start=False)

In [12]:
tpot.export('tpot_exported_pipeline_airdata.py')

True

In [13]:
print(tpot.score(X_test, y_test))

-4.802665750915752
